### ISSUE TITLE
Where would I install this?

### ISSUE THREAD

**Issue by awesomek29** [drewdorris/dynmap-borders#1]
I would like to check this out and use it on a server with my friends. Where do I install it?

**Comment by Demadunk** [comment]
You don't, cause this is a development for one specific server. Look up for towny plugins to go find out how to set up towny for your own server.

**Comment by drewdorris** [comment]
Hi, I plan on posting this resource on the Spigot forums soon. If you have Git/Maven you can pull this resource and compile it yourself, but there are some issues I still need to resolve.

**Comment by awesomek29** [comment]
@Demadunk  I would like country borders to be shown on my dynmap. I am using a 1:1000 scale

**Comment by Demadunk** [comment]
Oh, that. I'd leave it to drew to release when it's ready, because it's going through changes that much I know.
